config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :omniauthable, omniauth_providers: %i[github]

  validates :github_username, presence: true, uniqueness: { case_sensitive: false }

  # Want sign-up to authenticate with github_username (or email)

  attr_writer :login

  def login
    @login || self.github_username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(github_username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:github_username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create! do |user|
      user.email = auth.info.email if auth.info.email.present?
      user.github_username = auth.info.nickname
      user.password = Devise.friendly_token[0, 20]
      # user.image = auth.info.image
      # user.skip_confirmation!
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    added_attrs = [:github_username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @users = User.all
    @users_except_current = User.where.not(id: current_user.id).order("github_username")
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :github
  
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Github Contribution Charts for Batch-488</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= favicon_link_tag asset_path('octocat_favicon.png') %>
    
  </head>

  <body>
    <%#= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <!--<p class="notice"><%= notice %></p>-->
    <!--<p class="alert"><%= alert %></p>-->
  </body>
</html>

app/views/pages/_chart.html.erb
<!-- Prepare a container for calendar. -->
<div style="padding-left: 300px; padding-right: 300px;">
  <div class="user-info">
    <%= image_tag "https://avatars.githubusercontent.com/#{user.github_username}", class: "avatar", style: "margin-left: 10px;" %>
    <%= link_to "@#{user.github_username}", "http://github.com/#{user.github_username}", style: "margin-bottom: 0px; margin-right: 5px; color: #00cc00;", target: :_blank %>
  </div>
  <!--<div class="chart-<%= user.github_username %>">-->
  <div class="calendar-<%= user.github_username %>" style="min-height: 120px;">
    <img src="https://github.githubassets.com/images/spinners/octocat-spinner-128.gif" class="spinner"/>
  </div>
</div>

<script>
  GitHubCalendar(".calendar-<%= user.github_username %>", '<%= user.github_username %>', { responsive: true, summary_text: " ", global_stats: false, tooltips: true });
</script>

app/views/pages/home.html.erb
<!-- Include the library. -->
<script
  src="https://unpkg.com/github-calendar@latest/dist/github-calendar.min.js">
</script>

<!-- Default theme -->
<link
  rel="stylesheet"
  href="https://unpkg.com/github-calendar@latest/dist/github-calendar-responsive.css"/>

<!-- Additional customizations -->
<%= stylesheet_link_tag 'calendar' %>
<%# <link rel="stylesheet" href="app/assets/stylesheets/pages/_calendar.scss"/> %>


<div class="text-center mt-4">
  <h1>GitHub Contributions for Batch #488 (+ special Ruby luminaries)</h1>
  <p>Note: Contributions to private repositories may not show up.</p>
</div>

<!-- Display current user's chart first -->
<div class="chart-container">
  <%= render partial: "chart", locals: {user: current_user} %>
</div>

<% @users_except_current.all.each do |user| %>
  <div class="chart-container">
    <%= render partial: "chart", locals: {user: user} %>
  </div>
<% end %>

<script>
  // Remove default extra padding from chart bottom
  const removePaddingBottom = ((chartArea) => {
    chartArea.classList.remove("py-2");
    chartArea.classList.add("pt-2");
  });
  const chartAreas = document.querySelectorAll(".border.py-2.graph-before-activity-overview");
  chartAreas.forEach(removePaddingBottom);

  // Remove default min-height for chart
  const removeMinHeight = ((chart) => {
    chart.style.removeProperty("min-height");
  })
  const charts = document.querySelectorAll("div[class^='calendar-']");
  charts.forEach(removeMinHeight);
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%#= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png", class: "navbar-brand" %>
    <%# end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://avatars.githubusercontent.com/#{current_user.github_username}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Delete my account", registration_path(current_user), data: { confirm: "Are you sure you want to halt your transformation into an Octocat Ninja?" }, method: :delete, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", omniauth_authorize_path(resource_name, :github), class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>